src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json")
     */
    private $tags = [];

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $steps;

    /**
     * @ORM\Column(type="integer")
     */
    private $people;

    /**
     * @ORM\Column(type="integer")
     */
    private $budget;

    /**
     * @ORM\Column(type="integer")
     */
    private $difficulty;

    /**
     * @ORM\Column(type="integer")
     */
    private $preptime;

    /**
     * @ORM\ManyToMany(targetEntity=Ingredient::class, inversedBy="recipes", cascade={"persist"})
     */
    private $ingredients;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="recipes")
     */
    private $Author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="favories")
     */
    private $fav;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="location")
     */
    private $commentaires;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->fav = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTags(): ?array
    {
        return $this->tags;
    }

    public function setTags($tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getSteps(): ?string
    {
        return $this->steps;
    }

    public function setSteps($steps): self
    {
        $this->steps = $steps;

        return $this;
    }

    public function getPeople(): ?int
    {
        return $this->people;
    }

    public function setPeople(int $people): self
    {
        $this->people = $people;

        return $this;
    }

    public function getBudget(): ?int
    {
        return $this->budget;
    }

    public function setBudget(int $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(int $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getPreptime(): ?int
    {
        return $this->preptime;
    }

    public function setPreptime(int $preptime): self
    {
        $this->preptime = $preptime;

        return $this;
    }


    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }
    public function containIngredients($array): bool
    {
        if (count($array) == 0) return true;
        $contain = false;
        foreach ($this->getIngredients() as $ingredient) {
            foreach ($array as $id) {
                $match = false;
                if ($id == $ingredient->getId()) {
                    $match = true;
                    $contain = true;
                    continue;
                }
            }
            if ($match) continue;
        }
        return $contain;
    }
    public function containIngredientsCategorie($array): bool
    {
        if (count($array) == 0) return true;
        $contain = false;
        foreach ($this->getIngredients() as $ingredient) {
            foreach ($array as $id) {
                $match = false;
                if ($id == $ingredient->getType()->getId()) {
                    $match = true;
                    $contain = true;
                    continue;
                }
                if ($match) continue;
            }
        }
        return $contain;
    }
    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        $this->ingredients->removeElement($ingredient);

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFav(): Collection
    {
        return $this->fav;
    }

    public function addFav(User $fav): self
    {
        if (!$this->fav->contains($fav)) {
            $this->fav[] = $fav;
        }

        return $this;
    }

    public function removeFav(User $fav): self
    {
        $this->fav->removeElement($fav);

        return $this;
    }

    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setLocation($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getLocation() === $this) {
                $commentaire->setLocation(null);
            }
        }

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use App\Entity\User;
use App\Entity\Ingredient;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type as FormType;
use Symfony\Component\Validator\Constraints\File;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('photo', FileType::class, [
                'label' => 'image de votre recette',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([])
                ],
            ])
            ->add('ingredients',  EntityType::class, [
                'expanded' => true,
                'class' => Ingredient::class,
                'multiple' => true
            ])
            ->add('tags', FormType\CollectionType::class)
            ->add('steps')
            ->add('people')
            ->add('budget')
            ->add('difficulty')
            ->add('preptime')
            ->add('Author', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'pseudo'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Commentaires;
use App\Entity\Recipe;
use App\Entity\User;
use App\Form\CommentairesType;
use App\Repository\CommentairesRepository;
use App\Repository\RecipeRepository;
use App\Repository\UserRepository;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/recipe")
 */
class RecipeController extends AbstractController
{
    /**
     * @Route("/{id}/{editCom}", name="show_recipe",methods={"GET","POST"})
     */
    public function showRecipe($id, Request $request, Recipe $recipe = null, Commentaires $editCom = null, CommentairesRepository $commentaires): Response
    {

        $form = null;
        if ($recipe == null) return $this->redirectToRoute('app_home');
        if ($this->getUser()) {
            if ($editCom == null) {
                $commentaire = new Commentaires();
                $form = $this->createForm(CommentairesType::class, $commentaire);
                $form->handleRequest($request);
            } else {
                if ($editCom->getOwner() != $this->getUser() && !(in_array("ROLE_ADMIN", $this->getUser()->getRoles()))) return $this->redirectToRoute('show_recipe', ['id' => $id], Response::HTTP_SEE_OTHER);
                dump($form);
                $form = $this->createForm(CommentairesType::class, $editCom);
                $form->handleRequest($request);
            }
            if ($form->isSubmitted() && $form->isValid()) {
                if ($editCom) {
                    dump($editCom->getContent());
                    $commentaires->add($editCom, true);
                } else {
                    $commentaire->setDate(new DateTime());
                    $commentaire->setOwner($this->getUser());
                    $commentaire->setLocation($recipe);
                    $commentaires->add($commentaire, true);
                }

                return $this->redirectToRoute('show_recipe', ['id' => $id], Response::HTTP_SEE_OTHER);
            }
        }
        return $this->render('index.html.twig', [
            'form' => $form != null ? $form->createView() : null,
            'recipe' => $recipe,
            'ingredients' => $recipe->getIngredients(),
            'editedComId' => $editCom ? $editCom->getId() : null,
            'commentaires' => $recipe->getCommentaires(),
            'page_name' => 'showRecipe',
            'recipeAuthor' => $recipe->getAuthor()
        ]);
    }
    /**
     * @Route("/delete/commentaire/{id}", name="recipe_delete_commentaire",methods={"GET"})
     */
    public function deleteCommentaire($id, Commentaires $commentaire, CommentairesRepository $commentaires, UserRepository $users, RecipeRepository $recipes): Response
    {
        $user = $this->getUser();
        if (!$commentaire || !$user) return $this->redirectToRoute('app_home');
        if ($user != $commentaire->getOwner() && !in_array("ROLE_ADMIN", $user->getRoles())) return $this->redirectToRoute('show_recipe', ['id' => $commentaire->getLocation()->getId(), "editCom" => 'undefined'], Response::HTTP_SEE_OTHER);
        $userOwner = $commentaire->getOwner();
        $recipe = $commentaire->getLocation();

        $recipe->removeCommentaire($commentaire);
        $userOwner->removeCommentaire($commentaire);

        $commentaires->remove($commentaire, true);
        $users->add($userOwner, true);
        $recipes->add($recipe, true);

        return $this->redirectToRoute('show_recipe', ['id' => $recipe->getId()], Response::HTTP_SEE_OTHER);
    }
}

templates/recipe/index.html.twig
                    <a href="{{ path('user_recipe_create') }}">Créer une recette</a>
                         
                  <form class="pull-right hidden" role="search" id="nav-search-form" method="post" action="{{ path('searchRecipe') }}">
                    <div class="input-group" style="display :flex;flex-direction : column;width : 100%;justify-content : center;align-items : center">
                      <input type="text" class="form-control" placeholder="Search" name ="search" style="width : 90%">
                      <div style="display : flex; align-items : flex-start;width : 90%">
                        {% for triSection in triSections %}
                          <section style="display :flex;flex-direction : column;margin : 2%">
                            <h6>{{triSection[0]}}</h6>
                            {% for info in triSection[1] %}
                              <span>
                                <label for="checkbox|{{triSection[0]}}|{{info.id}}">{{info.name}}</label>
                                <input type="checkbox" name="checkbox|{{triSection[0]}}|{{info.id}}">
                              </span>
                            {% endfor %}
                          </section>
                        {% endfor %}
                        {% if app.user %}
                         <section style="display :flex;margin : 2%">
                          <label for="checkbox|ableToDoWithFridge">Possible de faire avec mes ingrédients</label>
                          <input type="checkbox" name="checkbox|ableToDoWithFridge">
                         </section>
                         {% endif %}
                      </div>
                      <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">Entrer</button>
                      </span>
                    </div>
                  </form>
                    <div style="display :flex;width : fit-content;flex-wrap: wrap">
                     {% for recipe in recipes %}
                     <div class="card" style="width : 15vw ;">
                     <img src="{{ asset('uploads/' ~ recipe.image) }}" class="card-img-top" alt="recipeimage" style="width : 100%">
                    <div class="card-body">
                     <h5 class="card-title">{{recipe.name}}</h5>
                       <p class="card-text" style="  text-overflow:ellipsis;overflow:hidden;display: -webkit-box !important;-webkit-line-clamp: 5;-webkit-box-orient: vertical;white-space: normal;">{{recipe.steps}}</p>
                        <a href="{{ path('show_recipe',{"id" : recipe.id})}}" class="btn btn-primary">Go</a>
                          {% if app.user %}
                          <a href="{{ path('user_like', {"id" : recipe.id }) }}">like</a>
                          {% endif %}
                          {# <img src='https://img.icons8.com/ios/64/-synthetidiamond-also-referred-to-as-laboratory-grown-diamond./hearts--v1.png' alt='test'>
                         <img src='https://img.icons8.com/office/64/-synthetidiamond-also-referred-to-as-laboratory-grown-diamond./hearts.png' alt='test1'> #}
                      </div>
                        </div>
                     {% endfor %}
                      </div>

templates/recipe/showRecipe.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
   <link href="/css/recipe1.css" rel="stylesheet" type="text/css"/>           
{% endblock %}   

{% block body %}
<html>
<body>
   
    <h1>{{recipe.name}}</h1>
    
    <div class="recipe">
      <img src="{{ asset('uploads/' ~ recipe.image) }}" class="card-img-top" alt="recipeimage" style="width : 300px">

      <p>
      <ul>
         <li>Steps : {{recipe.steps}}</li>
         <li>People : {{recipe.people}}</li>
         <li>Budget : {{recipe.budget}}</li>
         <li>Difficulty : {{recipe.difficulty}}</li>
         <li>Preptime : {{recipe.preptime}}</li>
         <li>Ingrédients nécéssaire : </li>
       
         <ul style="display : inline">
         {% for ingredient in ingredients %}
             <li style="display: inline;">{{ingredient.name}} </li>
         {% endfor %}
         </ul>
      </ul>
         {%  if recipe.Author != null %}
           <a href="{{path('get_user_profil',{"id" : recipeAuthor.id})}}">Auteur : {{recipeAuthor.pseudo}}</a>
         {% else %}
         <li>Auteur : deleted user</li>
         {% endif %}
      </p>

     {% if app.user and ('ROLE_ADMIN' in app.user.roles or (recipe.author != null and recipe.author.id == app.user.id))  %}
      <a class='admin' href="{{ path('user_recipe_delete', {"id" : recipe.id }) }}">Supprimer</a>
      <a class='admin' href="{{ path('user_recipe_edit', {"id" : recipe.id}) }}">Editer</a>
     {% endif %}
     {% if form is defined and form != null and editedComId == null  %}
     <div class="base_form">
       {{ include('base/_form.html.twig', {'button_label': "envoyer"}) }}
      </div>
       {% endif %}
       <h1>Commentaires : </h1>
     {% for commentaire in commentaires %}
    <div class="Commentaire-{{commentaire.id}}" style="border-bottom : 2px solid grey; width:100%;  display: block; margin-left: auto; margin-right: auto; padding-left: 1vw">
   {% if app.user and form != null and editedComId != null and editedComId == commentaire.id %}
       {{ include('base/_form.html.twig', {'button_label': "editer"}) }}       
    {% else %}
        <p> {{commentaire.content}}</p>
        <footer style="display:flex;justify-content : space-between">
        {%  if commentaire.owner != null %}
            <a href="{{path('get_user_profil',{"id" : commentaire.owner.id})}}">Envoyé par : {{commentaire.owner.pseudo}}</a>
         {% else %}
         <h5>envoyé par : deleted user </h5>
         {% endif %}
             <h5>le : {{commentaire.date|date("m/d/Y")}}</h5>
               {% if app.user and (commentaire in app.user.commentaires or "ROLE_ADMIN" in app.user.roles) %}
               <span>
                  <a href="{{ path('recipe_delete_commentaire', {"id": commentaire.id }) }}">Supprimer</a> 
                  <a href="{{path('show_recipe',{"id" : recipe.id ,"editCom" : commentaire.id })}}"> Modifier</a>
                  </span>
               {% endif %}
               </footer>

   {% endif %}
      </div>
     {% endfor %}
     
   </div>
</body>
</html>

{% endblock %}  